#!/bin/bash
# Definition des alias raccourcis
alias cdt="cd ~/test/"

# Definition des alias de git
alias ga="git add"
alias gb="git branch"
alias gcm="git commit -m"
alias gco="git checkout"
alias gpl="git pull"
alias gps="git push"
alias gm="git merge"
alias gu="git add -u"
alias gusm="git submodule foreach git pull"

# Definition des alias de ls
alias l="ls"
alias ll="ls -l"
alias la="ls -lA"
alias lah="ls -lAh"
alias lh="ls -lh"
alias ls="ls --color"

# Definition des alias de compilation
alias gccf="gcc -Wall -Wextra -Werror"
alias g++f="g++ -Wall -Wextra -Werror"

# Definition des alias
alias auteur="echo 'mdelage' > auteur"
alias clean="find . -name '*~' -execdir rm {} \;"
alias modsh="vim ~/dotfiles/.zshrc"
alias purgevim="rf -f ~/.vim/tmp/*.swp ~/.vim/tmp/.*.swp"

# Laravel aliases
alias artisan="php artisan"
